
import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'pt' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: 'Welcome to the Paddock',
    login: 'Login',
    signup: 'Sign Up',
    howToPlay: 'How to Play & Scoring',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    age: 'Age',
    country: 'Country',
    terms: 'I agree to the Terms and Conditions',
    raceNow: 'Race Now',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
    rankings: 'Global Rankings',
    leagues: 'Leagues',
    placeBet: 'Place Prediction',
    bettingClosed: 'Betting Closed',
    entryFee: 'Entry Fee',
    prizePool: 'Prize Pool',
    multiplier: 'Multiplier',
    confirmBet: 'Confirm Bet',
    pointsBreakdown: 'Points Breakdown',
    exactMatch: 'Exact Match',
    partialMatch: 'Partial Match',
    howToBet: 'How to Bet',
    detailedScoring: 'Detailed Scoring',
    socialLeagues: 'Social & Leagues',
    welcomeTab: 'Welcome',
    acceptTerms: 'Accept Terms & Race!',
    manualTitle: 'F1™ Poolers: Sporting Regulations',
    // Welcome walkthrough
    welcomeTitle: 'Welcome to F1™ Poolers',
    welcomeSubtitle: 'The ultimate F1 prediction game. Outsmart your rivals, climb the rankings and prove you know Formula 1 better than anyone.',
    howItWorksTitle: 'How It Works',
    howItWorksStep1Title: 'Pick a Session',
    howItWorksStep1Desc: 'Each Grand Prix weekend has multiple sessions: Qualifying, Sprint and Race. Choose which one you want to predict.',
    howItWorksStep2Title: 'Predict the Top 5',
    howItWorksStep2Desc: 'Select 5 drivers (or teams) and place them in order from P1 to P5. That\'s your prediction slip.',
    howItWorksStep3Title: 'Earn Points & Coins',
    howItWorksStep3Desc: 'After the session, your predictions are scored. Exact position matches earn big points; having the right driver in the top 5 but wrong slot still earns a partial bonus.',
    whatAreFunCoinsTitle: 'What are Fun-Coins?',
    whatAreFunCoinsDesc: 'Fun-Coins are the in-game currency you use to place predictions. They are NOT real money — this is a free strategy game. You receive 50 free Fun-Coins every time a new race weekend opens, so you can always play.',
    whatAreFunCoinsExtra: 'The more Fun-Coins you have, the more predictions you can place across different sessions — giving you more chances to score points and climb the leaderboard!',
    whatArePointsTitle: 'What are Points?',
    whatArePointsDesc: 'Points are your score. They determine your position on the Global Leaderboard and inside your Leagues. The more accurate your predictions, the more points you earn. Points accumulate across the entire season.',
    bettingStrategyTitle: 'Betting Strategy Tips',
    strategyTip1Title: 'Bet Early',
    strategyTip1Desc: 'Predictions placed days before the session lock in a higher multiplier (up to 5×), massively boosting your points.',
    strategyTip2Title: 'Drivers vs Teams',
    strategyTip2Desc: 'Driver bets pay more points but are harder to nail. Team bets give you double the coverage (two cars) at 50% points — great for unpredictable sessions.',
    strategyTip3Title: 'Combo Bets',
    strategyTip3Desc: 'Submit both a Driver AND a Team prediction on the same session for a Combo bet. It costs more Fun-Coins but you earn points from both slips.',
    strategyTip4Title: 'Chase the Jackpot',
    strategyTip4Desc: 'If you predict the exact P1-P5 drivers in the correct order, you trigger the Jackpot Protocol and win a share of the entire prize pool! If nobody nails it, the prize pool rolls over to the same event in the next round — making the jackpot even bigger!',
    readyToRace: 'Ready to race? Explore the other tabs for detailed scoring tables, multiplier mechanics and league features.',
    langSelect: 'Choose Language',
    multiplierTiers: 'The Multiplier System',
    article1: 'Article 1.0: Point Allocation',
    article1_1: 'Article 1.1: Constructor Strategy',
    article1_2: 'Article 1.2: The Grand Jackpot',
    article2: 'Article 2.0: Timing Multipliers',
    economyTitle: 'Fun-Coin Economy & Earnings',
    roundBonus: 'Round Bonus',
    adRewards: 'Ad-Rewards',
    storeBundles: 'Store Bundles',
    jackpotShares: 'Jackpot Shares',
    chooseStrategy: 'Choose Strategy',
    theGrid: 'The Grid',
    finalize: 'Finalize',
    platinum: 'Platinum',
    gold: 'Gold',
    silver: 'Silver',
    standard: 'Standard',
    economyDesc: 'Every time a new race weekend is added to the calendar, every active player receives 50 Fun-Coins automatically to ensure the grid stays full.',
    adRewardsDesc: 'Having more Fun-Coins means you can place more predictions on different sessions and event types, maximizing your chances to earn points and win big.',
    storeBundlesDesc: 'For high-rollers looking to join multiple leagues or high-entry events, "Championship Vaults" and "Racer Bundles" are available in the store.',
    betStep1: 'Choose between Individual Drivers or Constructors.',
    betStep2: 'Tap a driver/team from the grid then select a prediction slot (P1-P5).',
    betStep3: 'Hit Confirm Prediction to lock in your position and current multiplier.',
    multiplierIntro: 'The multiplier system rewards early analysis. The sooner you lock in your prediction before the session start, the higher your final score will be.',
    multiplierLock: 'The multiplier is permanently locked the moment you click "Confirm Prediction". Changing your prediction after confirmation will result in applying the current multiplier of the new confirmation time.',
    constructorStrategyDesc: 'Team bets function as a hedge. You earn 50% of the Driver points if any driver from that team finishes in your predicted spot.',
    jackpotProtocolDesc: 'A "Perfect Prediction" (matching the exact P1-P5 Drivers in order) triggers the Jackpot Protocol. The total accumulated prize pool is split equally among all players who nail the perfect result. If no one achieves a Perfect Prediction, the entire prize pool rolls over to the same event type in the next round, growing the jackpot until someone claims it!',
    leagueIntro: 'Competing globally is the standard; competing in your own League is where legends are made. Leagues are private or public communities where you race against your inner circle.',
    privacyProtocol: 'Privacy Protocol: Admins can lock leagues with unique invite codes. Only verified members can enter the simulation.',
    customTrophies: 'Custom Trophies: League admins can set specific "Physical" or "Digital" prizes (e.g., custom merch or titles) for their season winners.',
    fullModeration: 'Full Moderation: Admins have the power to suspend or ban members who violate the sporting code of conduct.',
    paddockChatIntro: 'The Paddock Chat: Real-time telemetry and discussion.',
    globalRankHighlight: 'Global Rank Highlighting: Top-ranked global players are automatically highlighted in league chats with "High Roller" badges.',
    realTimeTelemetry: 'Real-time Telemetry: Chat about race results instantly with encrypted league communication.',
    reactionsDesc: 'Reactions: Like or dislike predictions shared in chat to show your support or rivalry.',
    driverPredictionsDesc: 'Predict the exact finish order of the top 5 drivers. Exact matches award maximum points. Partial matches (driver in top 5 but wrong position) award a flat safety bonus.',
    teamPredictionsDesc: 'Teams award 50% of the total Driver points for that position. If either car from your chosen team finishes in the predicted slot, you earn the points. This is a lower-risk strategy ideal for chaotic sessions.',
    teamMainRacePoints: 'Team Main Race Points:',
    teamStrategyAdvantages: 'Team Strategy Advantages:',
    doubleCarCoverage: 'Double Car Coverage',
    safetyPartialPoints: 'Safety Partial Points',
    jackpotEligibility: 'Jackpot Eligibility',
    jackpotTrigger: 'Only exact P1-P5 Driver predictions trigger this protocol. Unclaimed jackpots roll over to the next round!',
    leagueTelemetry: 'LEAGUE TELEMETRY',
    createYourPaddock: 'Create Your Paddock',
    createPaddockDesc: 'Start private leagues for your coworkers, family, or global race fans. Customize the name, description, and accessibility of your simulation room.',
    customTrophiesRewards: 'Custom Trophies & Rewards',
    customTrophiesDesc: 'Admins can define seasonal prizes, including physical items or digital titles. Create stakes that matter to your group and track who dominates the podium.',
    socialCommunication: 'Social Communication',
    chatExample1: 'Max is definitely taking P1 this weekend!',
    chatExample2: 'No way, did you see the Ferrari pace in FP2?',
    realTimeChat: 'Real-Time Chat:',
    realTimeChatDesc: 'Instant paddock telemetry and banter between sessions.',
    reactions: 'Reactions:',
    reactionsFeatureDesc: 'Like or dislike predictions to fuel the competitive fire.',
    highRollerBadges: 'High Roller Badges:',
    highRollerBadgesDesc: 'Top global players are automatically identified in league chats.',
    moderation: 'Moderation:',
    moderationDesc: 'Admins can suspend or ban users to keep the environment sporting.',
    messageClearNote: 'Note: Messages are automatically cleared after 10 days to keep the paddock fresh.',
    multiplierMechanics: 'Multiplier Mechanics',
    driverPredictions: 'Driver Predictions',
    teamPredictions: 'Team Predictions',
    perfectScore: 'Perfect Score',
    mainRace: 'Main Race',
    qualifying: 'Qualifying',
    sprintRace: 'Sprint Race',
    pos: 'Pos',
    exact: 'Exact',
    anyT5: 'Any T5',
    tapGrid: 'Tap Grid',
    selectSlot: 'Select Slot',
    tapAnyDriver: 'Tap any driver from the grid, then select your desired P1-P5 spot.',
    termsAgree: 'I agree to the',
    termsAndConditions: 'Terms and Conditions',
    close: 'Close',
    biometricLogin: 'Login with Biometrics',
    passwordMustBe5Digits: 'Password must be exactly 5 numbers',
    passwordHint: '5 digits only (e.g. 12345)',
    statistics: 'Season Statistics',
    statsNoData: 'No Statistics Available',
    statsNoDataDesc: 'Results will appear here once events are completed.',
    statsEventsRecorded: 'Events Recorded',
    statDrivers: 'Drivers',
    statTeams: 'Teams',
    statDriver: 'Driver',
    statTeam: 'Team',
    statPts: 'PTS',
    statWins: 'Wins',
    statPodiums: 'Podiums',
    statTop5: 'Top 5',
    statEntries: 'Entries',
    statAvgPos: 'Avg Pos',
    statBestPos: 'Best',
    statEventBreakdown: 'Event Breakdown',
    statFilter_all: 'All',
    statFilter_race: 'Race',
    statFilter_qualifying: 'Qualifying',
    statFilter_sprint: 'Sprint',
    usernameHint: 'Max 8 characters, no spaces',
    usernameInvalid: 'Username must be max 8 characters with no spaces',
    recoveryTitle: 'Add Recovery Contact',
    recoveryMessage: 'We recommend adding an email or phone number to your profile. This is the only way to recover your credentials if you forget or lose them. F1 Poolers will never send messages to your contact information — it is used solely for account recovery.',
    recoveryGoToProfile: 'Go to Profile',
    recoveryDismissBtn: 'Not now, I will risk lose my points',
    inviteFriends: 'Invite your friends to compete with you',
    inviteShareVia: 'Share via',
    inviteCopied: 'Copied!',
    inviteCopyUrl: 'Copy URL',
    inviteMessage: 'Think you can outscore me in F1 predictions? \u{1F3CE}\u{FE0F} Join me on F1 Poolers \u2014 pick your Top 5 drivers & teams, climb the leaderboard, and prove who\'s the real paddock champion! Free to play, pure bragging rights. Let\'s race! \u{1F3C1}',
    inviteMessageShort: 'Think you can beat my F1 predictions? \u{1F3CE}\u{FE0F} Join me on F1 Poolers! Free, fun & competitive.',
    inviteEmailSubject: 'Join me on F1 Poolers! \u{1F3CE}\u{FE0F}',
    inviteInstagramHint: 'Message copied! Paste it on Instagram.',
    // UserSettings
    userSettings: 'User Settings',
    profile: 'Profile',
    myLeagues: 'My Leagues',
    memberSince: 'Member since',
    avatarHint: 'Click the camera icon to upload a new avatar (max 2MB)',
    recoveryContactLabel: 'Recovery Contact',
    recoveryContactHint: 'Add an email or phone so you can recover your account if you forget your credentials. We will never send messages to these contacts.',
    email: 'Email',
    phone: 'Phone',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated!',
    profileUpdateFailed: 'Failed to update profile.',
    imageTooLarge: 'Image must be less than 2MB',
    timezone: 'Timezone',
    timezoneHint: 'All event times are shown in your timezone. Change it here if needed.',
    leaguesYouManage: 'Leagues You Manage',
    leaguesClickToView: 'Click a league to view details or invite friends.',
    noLeaguesYet: "You haven't created any leagues yet.",
    privateLabel: 'Private',
    publicLabel: 'Public',
    membersLabel: 'Members',
    // Header
    notificationsTitle: 'Notifications',
    noNotifications: 'No notifications',
    markAsRead: 'Mark as read',
    // Leaderboard
    globalRankings: 'Global Rankings',
    // RaceSelector
    upcomingRounds: 'Upcoming Rounds',
    activeRound: 'Active Round',
    pastRounds: 'Past Rounds',
    noActiveRound: 'No active round — check back when the next Grand Prix begins!',
    allEventsFinished: 'All events finished',
    viewResults: 'View Results',
    live: 'LIVE',
    finished: 'FINISHED',
    // BetConfirmation
    betConfirmed: 'Bet Confirmed!',
    yourSlipFor: 'Your slip for the',
    entryFeePaid: 'Entry Fee Paid:',
    goodLuck: 'Good Luck!',
    // Share
    sharePrediction: 'Share Prediction',
    sharing: 'Sharing...',
    shared: 'Shared!',
    copiedToClipboard: 'Copied!',
    downloadImage: 'Download Image',
    predictionsPlaced: 'prediction(s) placed',
    share: 'Share',
    copied: 'Copied',
    combo: 'Combo',
    // BettingModal
    p5Slip: 'P5 Slip',
    slotsUsed: 'Slots Used',
    limitReachedMsg: 'Limit Reached for this session! Try other events in this Round.',
    betsRemainingMsg: 'You can still place more bets for this session.',
    tapHint: 'Tap a driver or team from the grid, then select an available prediction slot.',
    drivers: 'Drivers',
    teams: 'Teams',
    availableLabel: 'Available',
    predictionLabel: 'Prediction',
    constructorSlot: 'Constructor Slot',
    awaiting: 'Awaiting...',
    selectP: 'Select P',
    singleLabel: 'Single',
    comboLabel: 'Combo',
    tryDifferentSession: 'Try a different session in this Grand Prix!',
    cancel: 'Cancel',
    back: 'Back',
    chooseOtherEvent: 'Choose Other Event',
    wait: 'Wait...',
    driversOnly: 'Drivers Only',
    teamsOnly: 'Teams Only',
    bothCombo: 'Both (Combo)',
    fillAllSlotsBoth: 'Please fill all 5 slots for both Drivers and Teams.',
    fillAllSlots: 'Please fill all 5 prediction slots.',
    betLimitReached: 'You have already reached the limit of bets for this session.',
    diversifyRound: 'Diversify Round',
    predict: 'Predict',
    mult: 'Mult',
    of: 'of',
    // LeagueLeaderboard
    leagueNamePlaceholder: 'League Name',
    shortDescPlaceholder: 'Short Description',
    enableChat: 'Enable Chat',
    addPrize: 'Add Prize',
    prizeTitlePlaceholder: 'Prize Title (Max 40 chars)',
    imageUrlPlaceholder: 'Upload Image',
    uploadPrizeImage: 'Upload Prize Image',
    imageUploaded: 'Image Uploaded ✓',
    prizeRulesPlaceholder: 'Prize Rules & Description (Max 500 chars)',
    remaining: 'remaining',
    createBtn: 'Create',
    joined: 'Joined',
    // LeagueDetails
    generalScoreboard: 'General Scoreboard',
    eventHistoryTab: 'Event History',
    paddockChat: 'Paddock Chat',
    joining: 'Joining...',
    joinGrid: 'Join Grid',
    leaveLeague: 'Leave League',
    copyInviteBtn: 'Copy Invite',
    inviteMemberPlaceholder: 'Invite member by username...',
    sendInvite: 'Send Invite',
    seasonPts: 'Season PTS',
    unsuspend: 'Unsuspend',
    suspend: 'Suspend',
    banUser: 'Ban User',
    pastSessions: 'Past Sessions Scoreboards',
    leagueEntries: 'League Entries',
    viewScoreboardLink: 'View Scoreboard',
    noEventsYet: 'No events completed for this season yet.',
    leagueCommandCentre: 'League Command Centre',
    enableTelemetry: 'Enable Member Telemetry (Chat)',
    customSeasonalPrize: 'Custom Seasonal Prize',
    prizeDesignation: 'Prize Designation',
    prizeDesignationPlaceholder: 'e.g. Legendary Gold Helmet',
    visualEvidence: 'Visual Evidence (Upload Image)',
    sportingRegulations: 'Sporting Regulations (Rules)',
    describePrize: 'Describe how members win this prize...',
    finalizeChanges: 'Finalize Sporting Changes',
    seasonPrizeLabel: 'Season Prize:',
    enterInviteCode: 'Enter Invite Code:',
    leaveConfirm: 'Are you sure you want to leave this league?',
    inviteLinkCopied: 'Invite link copied!',
    invitationSent: 'Invitation sent to',
    leagueSettingsUpdated: 'League settings updated!',
    confirmAction: 'Confirm action:',
    round: 'Round',
    // RaceResults
    resultsLabel: 'Results:',
    officialClassification: 'Official Classification',
    podiumPayouts: 'Podium & Payouts',
    fullScoreboard: 'Full Scoreboard',
    officialTop5: 'Official Top 5',
    prizeDistribution: 'Prize Distribution',
    totalPurse: 'Total Purse',
    winnersLabel: 'Winners',
    participantLabel: 'Participant',
    pointsLabel: 'Points',
    prizeLabel: 'Prize',
    viewAllEntries: 'View all entries in Scoreboard',
    noParticipantsEarned: 'No participants earned points in this session.',
    eventScoreboard: 'Event Scoreboard',
    searchUser: 'Search user...',
    rankLabel: 'Rank',
    userLabel: 'User',
    p15Prediction: 'P1-P5 Prediction',
    noEntriesFound: 'No entries found matching your search.',
    noPrediction: 'No prediction',
    // LeagueChat
    bannedFromLeague: 'You have been banned from this league.',
    leagueChatTitle: 'League Chat',
    messagesRemovedNote: 'Messages are removed after 10 days.',
    suspendedFromChat: 'You are suspended from chat',
    typeMessage: 'Type a message...',
    // GetCoins
    getCoins: 'Get Fun Coins',
    freeRewards: 'Free Rewards',
    watchEarn: 'Watch & Earn',
    watchAdDesc: 'Watch a short sponsorship clip from our partners to earn free coins for your next prediction.',
    adPlaying: 'Ad Playing...',
    watchAd: 'Watch Ad',
    adRewardsDisabled: 'Ad rewards currently disabled.',
    coinsAdded: 'Coins Added!',
    // Auth errors
    passwordsDontMatch: "Passwords don't match",
    minAge18: 'Minimum age is 18',
    pleaseAcceptTerms: 'Please accept terms and conditions',
    selectCountry: 'Select...',
    locationNotice: 'Your location will be automatically detected to set your country.',
    leaveSiteTitle: 'Leaving F1™ Poolers?',
    leaveSiteMessage: 'Are you sure you want to leave the site?',
    leaveSiteStay: 'No, stay on F1™ Poolers',
    leaveSiteLeave: 'Yes, leave the site'
  },
  pt: {
    signup: 'Cadastrar',
    howToPlay: 'Como Jogar e Pontuação',
    username: 'Usuário',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    age: 'Idade',
    country: 'País',
    terms: 'Eu concordo com os Termos e Condições',
    raceNow: 'Correr Agora',
    dashboard: 'Painel',
    adminPanel: 'Painel Admin',
    rankings: 'Ranking Global',
    leagues: 'Ligas',
    placeBet: 'Fazer Palpite',
    bettingClosed: 'Apostas Encerradas',
    entryFee: 'Taxa de Entrada',
    prizePool: 'Prêmio Total',
    multiplier: 'Multiplicador',
    confirmBet: 'Confirmar Aposta',
    pointsBreakdown: 'Distribuição de Pontos',
    exactMatch: 'Acerto Exato',
    partialMatch: 'Acerto Parcial',
    howToBet: 'Como Apostar',
    detailedScoring: 'Pontuação Detalhada',
    socialLeagues: 'Social e Ligas',
    welcomeTab: 'Bem-vindo',
    acceptTerms: 'Aceitar Termos e Correr!',
    manualTitle: 'F1™ Poolers: Regulamento Esportivo',
    welcomeTitle: 'Bem-vindo ao F1™ Poolers',
    welcomeSubtitle: 'O jogo definitivo de previsão de F1. Supere seus rivais, suba no ranking e prove que você entende de Fórmula 1 melhor que qualquer um.',
    howItWorksTitle: 'Como Funciona',
    howItWorksStep1Title: 'Escolha uma Sessão',
    howItWorksStep1Desc: 'Cada fim de semana de Grande Prêmio tem várias sessões: Qualificação, Sprint e Corrida. Escolha qual você quer prever.',
    howItWorksStep2Title: 'Preveja o Top 5',
    howItWorksStep2Desc: 'Selecione 5 pilotos (ou equipes) e coloque-os em ordem de P1 a P5. Esse é o seu boletim de previsão.',
    howItWorksStep3Title: 'Ganhe Pontos e Moedas',
    howItWorksStep3Desc: 'Após a sessão, suas previsões são pontuadas. Acertos exatos de posição rendem muitos pontos; ter o piloto certo no top 5 mas na posição errada ainda rende um bônus parcial.',
    whatAreFunCoinsTitle: 'O que são Fun-Coins?',
    whatAreFunCoinsDesc: 'Fun-Coins são a moeda do jogo que você usa para fazer previsões. NÃO são dinheiro real — este é um jogo de estratégia gratuito. Você recebe 50 Fun-Coins grátis toda vez que um novo fim de semana de corrida abre, então você sempre pode jogar.',
    whatAreFunCoinsExtra: 'Quanto mais Fun-Coins você tiver, mais previsões poderá fazer em diferentes sessões — dando mais chances de marcar pontos e subir no ranking!',
    whatArePointsTitle: 'O que são Pontos?',
    whatArePointsDesc: 'Pontos são sua pontuação. Eles determinam sua posição no Ranking Global e dentro das suas Ligas. Quanto mais precisas suas previsões, mais pontos você ganha. Os pontos acumulam durante toda a temporada.',
    bettingStrategyTitle: 'Dicas de Estratégia',
    strategyTip1Title: 'Aposte Cedo',
    strategyTip1Desc: 'Previsões feitas dias antes da sessão travam um multiplicador mais alto (até 5×), aumentando massivamente seus pontos.',
    strategyTip2Title: 'Pilotos vs Equipes',
    strategyTip2Desc: 'Apostas em pilotos pagam mais pontos, mas são mais difíceis de acertar. Apostas em equipes dão o dobro de cobertura (dois carros) com 50% dos pontos — ótimo para sessões imprevisíveis.',
    strategyTip3Title: 'Apostas Combo',
    strategyTip3Desc: 'Envie uma previsão de Piloto E uma de Equipe na mesma sessão para uma aposta Combo. Custa mais Fun-Coins, mas você ganha pontos de ambos os boletins.',
    strategyTip4Title: 'Busque o Jackpot',
    strategyTip4Desc: 'Se você prever os pilotos exatos de P1-P5 na ordem correta, você ativa o Protocolo Jackpot e ganha uma parte de todo o prêmio acumulado! Se ninguém acertar, o prêmio acumula para o mesmo evento na próxima rodada — tornando o jackpot ainda maior!',
    readyToRace: 'Pronto para correr? Explore as outras abas para tabelas de pontuação detalhadas, mecânica de multiplicadores e funcionalidades de liga.',
    langSelect: 'Escolha o Idioma',
    multiplierTiers: 'O Sistema de Multiplicadores',
    article1: 'Artigo 1.0: Alocação de Pontos',
    article1_1: 'Artigo 1.1: Estratégia de Construtores',
    article1_2: 'Artigo 1.2: O Grande Jackpot',
    article2: 'Artigo 2.0: Multiplicadores de Tempo',
    economyTitle: 'Economia e Ganhos de Fun-Coins',
    roundBonus: 'Bônus de Rodada',
    adRewards: 'Recompensas de Anúncios',
    storeBundles: 'Pacotes da Loja',
    jackpotShares: 'Cotas do Jackpot',
    chooseStrategy: 'Escolha a Estratégia',
    theGrid: 'O Grid',
    finalize: 'Finalizar',
    platinum: 'Platina',
    gold: 'Ouro',
    silver: 'Prata',
    standard: 'Padrão',
    economyDesc: 'Toda vez que um novo fim de semana de corrida é adicionado ao calendário, cada jogador ativo recebe 50 Fun-Coins automaticamente para garantir que o grid continue cheio.',
    adRewardsDesc: 'Ter mais Fun-Coins significa que você pode fazer mais previsões em diferentes sessões e tipos de eventos, maximizando suas chances de ganhar pontos e vencer.',
    storeBundlesDesc: 'Para os grandes apostadores que desejam participar de várias ligas ou eventos de alta entrada, "Cofres de Campeonato" e "Pacotes de Piloto" estão disponíveis na loja.',
    betStep1: 'Escolha entre Pilotos Individuais ou Construtores.',
    betStep2: 'Toque em um piloto/equipe do grid e selecione um slot de previsão (P1-P5).',
    betStep3: 'Clique em Confirmar Previsão para travar sua posição e o multiplicador atual.',
    multiplierIntro: 'O sistema de multiplicadores recompensa a análise antecipada. Quanto mais cedo você travar seu palpite antes do início da sessão, maior será sua pontuação final.',
    multiplierLock: 'O multiplicador é travado permanentemente no momento em que você clica em "Confirmar Previsão". Alterar seu palpite após a confirmação resultará na aplicação do multiplicador atual no momento da nova confirmação.',
    constructorStrategyDesc: 'Apostas em equipe funcionam como uma proteção. Você ganha 50% dos pontos de Piloto se qualquer piloto dessa equipe terminar na posição prevista.',
    jackpotProtocolDesc: 'Um "Palpite Perfeito" (acertar os pilotos exatos de P1-P5 em ordem) ativa o Protocolo de Jackpot. O prêmio total acumulado é dividido igualmente entre todos os jogadores que acertarem o resultado perfeito. Se ninguém conseguir um Palpite Perfeito, todo o prêmio acumula para o mesmo tipo de evento na próxima rodada, aumentando o jackpot até que alguém o conquiste!',
    leagueIntro: 'Competir globalmente é o padrão; competir em sua própria Liga é onde as lendas são feitas. As ligas são comunidades privadas ou públicas onde você corre contra seu círculo interno.',
    privacyProtocol: 'Protocolo de Privacidade: Os administradores podem trancar as ligas com códigos de convite exclusivos. Apenas membros verificados podem entrar na simulação.',
    customTrophies: 'Troféus Personalizados: Os administradores da liga podem definir prêmios "Físicos" ou "Digitais" específicos (ex: mercadorias personalizadas ou títulos) para os vencedores da temporada.',
    fullModeration: 'Moderação Total: Os administradores têm o poder de suspender ou banir membros que violem o código de conduta esportiva.',
    paddockChatIntro: 'O Chat do Paddock: Telemetria e discussão em tempo real.',
    globalRankHighlight: 'Destaque de Ranking Global: Os melhores jogadores do ranking global são destacados automaticamente nos chats da liga com emblemas de "Apostador VIP".',
    realTimeTelemetry: 'Telemetria em Tempo Real: Converse sobre os resultados das corridas instantaneamente com comunicação criptografada da liga.',
    reactionsDesc: 'Reações: Curta ou descurta palpites compartilhados no chat para mostrar seu apoio ou rivalidade.',
    driverPredictionsDesc: 'Preveja a ordem exata de chegada dos 5 primeiros pilotos. Acertos exatos concedem pontos máximos. Acertos parciais (piloto no top 5 mas posição errada) concedem um bônus de segurança fixo.',
    teamPredictionsDesc: 'Equipes concedem 50% do total de pontos de Piloto para aquela posição. Se qualquer carro da sua equipe escolhida terminar no slot previsto, você ganha os pontos. Esta é uma estratégia de menor risco ideal para sessões caóticas.',
    teamMainRacePoints: 'Pontos de Corrida Principal por Equipe:',
    teamStrategyAdvantages: 'Vantagens da Estratégia por Equipe:',
    doubleCarCoverage: 'Cobertura de Dois Carros',
    safetyPartialPoints: 'Pontos Parciais de Segurança',
    jackpotEligibility: 'Elegibilidade para Jackpot',
    jackpotTrigger: 'Apenas previsões exatas de Pilotos P1-P5 ativam este protocolo. Jackpots não conquistados acumulam para a próxima rodada!',
    leagueTelemetry: 'TELEMETRIA DA LIGA',
    createYourPaddock: 'Crie Seu Paddock',
    createPaddockDesc: 'Inicie ligas privadas para seus colegas de trabalho, família ou fãs de corrida globais. Personalize o nome, descrição e acessibilidade da sua sala de simulação.',
    customTrophiesRewards: 'Troféus e Recompensas Personalizadas',
    customTrophiesDesc: 'Administradores podem definir prêmios sazonais, incluindo itens físicos ou títulos digitais. Crie apostas que importam para seu grupo e acompanhe quem domina o pódio.',
    socialCommunication: 'Comunicação Social',
    chatExample1: 'Max definitivamente vai ficar em P1 neste fim de semana!',
    chatExample2: 'De jeito nenhum, você viu o ritmo da Ferrari no TL2?',
    realTimeChat: 'Chat em Tempo Real:',
    realTimeChatDesc: 'Telemetria instantânea do paddock e conversa entre as sessões.',
    reactions: 'Reações:',
    reactionsFeatureDesc: 'Curta ou descurta previsões para alimentar o fogo competitivo.',
    highRollerBadges: 'Emblemas Apostador VIP:',
    highRollerBadgesDesc: 'Os melhores jogadores globais são identificados automaticamente nos chats da liga.',
    moderation: 'Moderação:',
    moderationDesc: 'Administradores podem suspender ou banir usuários para manter o ambiente esportivo.',
    messageClearNote: 'Nota: As mensagens são automaticamente limpas após 10 dias para manter o paddock fresco.',
    multiplierMechanics: 'Mecânica dos Multiplicadores',
    driverPredictions: 'Previsões de Pilotos',
    teamPredictions: 'Previsões de Equipes',
    perfectScore: 'Pontuação Perfeita',
    mainRace: 'Corrida Principal',
    qualifying: 'Qualificação',
    sprintRace: 'Corrida Sprint',
    pos: 'Pos',
    exact: 'Exato',
    anyT5: 'Qualquer T5',
    tapGrid: 'Toque no Grid',
    selectSlot: 'Selecione o Slot',
    tapAnyDriver: 'Toque em qualquer piloto do grid e selecione sua posição desejada P1-P5.',
    termsAgree: 'Eu concordo com os',
    termsAndConditions: 'Termos e Condições',
    close: 'Fechar',
    biometricLogin: 'Entrar com Biometria',
    passwordMustBe5Digits: 'A senha deve ter exatamente 5 números',
    passwordHint: 'Apenas 5 dígitos (ex: 12345)',
    statistics: 'Estatísticas da Temporada',
    statsNoData: 'Sem Estatísticas Disponíveis',
    statsNoDataDesc: 'Os resultados aparecerão aqui quando os eventos forem concluídos.',
    statsEventsRecorded: 'Eventos Registrados',
    statDrivers: 'Pilotos',
    statTeams: 'Equipes',
    statDriver: 'Piloto',
    statTeam: 'Equipe',
    statPts: 'PTS',
    statWins: 'Vitórias',
    statPodiums: 'Pódios',
    statTop5: 'Top 5',
    statEntries: 'Entradas',
    statAvgPos: 'Pos Méd',
    statBestPos: 'Melhor',
    statEventBreakdown: 'Detalhamento por Evento',
    statFilter_all: 'Todos',
    statFilter_race: 'Corrida',
    statFilter_qualifying: 'Qualificação',
    statFilter_sprint: 'Sprint',
    usernameHint: 'Máx 8 caracteres, sem espaços',
    usernameInvalid: 'Usuário deve ter no máximo 8 caracteres sem espaços',
    recoveryTitle: 'Adicionar Contato de Recuperação',
    recoveryMessage: 'Recomendamos adicionar um email ou telefone ao seu perfil. Esta é a única forma de recuperar suas credenciais caso você esqueça ou perca. O F1 Poolers nunca enviará mensagens para seu contato — ele é usado apenas para recuperação de conta.',
    recoveryGoToProfile: 'Ir para o Perfil',
    recoveryDismissBtn: 'Agora não, vou arriscar perder meus pontos',
    inviteFriends: 'Convide seus amigos para competir com você',
    inviteShareVia: 'Compartilhar via',
    inviteCopied: 'Copiado!',
    inviteCopyUrl: 'Copiar URL',
    inviteMessage: 'Acha que pode me superar nas previsões de F1? \u{1F3CE}\u{FE0F} Junte-se a mim no F1 Poolers \u2014 escolha seus Top 5 pilotos e equipes, suba no ranking e prove quem é o verdadeiro campeão do paddock! Grátis para jogar, pura diversão. Vamos correr! \u{1F3C1}',
    inviteMessageShort: 'Acha que pode superar minhas previsões de F1? \u{1F3CE}\u{FE0F} Junte-se a mim no F1 Poolers! Grátis, divertido e competitivo.',
    inviteEmailSubject: 'Junte-se a mim no F1 Poolers! \u{1F3CE}\u{FE0F}',
    inviteInstagramHint: 'Mensagem copiada! Cole no Instagram.',
    userSettings: 'Configurações',
    profile: 'Perfil',
    myLeagues: 'Minhas Ligas',
    memberSince: 'Membro desde',
    avatarHint: 'Clique no ícone da câmera para enviar um novo avatar (máx 2MB)',
    recoveryContactLabel: 'Contato de Recuperação',
    recoveryContactHint: 'Adicione um email ou telefone para recuperar sua conta caso esqueça suas credenciais. Nunca enviaremos mensagens para esses contatos.',
    email: 'Email',
    phone: 'Telefone',
    saving: 'Salvando...',
    saveChanges: 'Salvar Alterações',
    profileUpdated: 'Perfil atualizado!',
    profileUpdateFailed: 'Falha ao atualizar perfil.',
    imageTooLarge: 'A imagem deve ter menos de 2MB',
    timezone: 'Fuso Horário',
    timezoneHint: 'Todos os horários dos eventos são exibidos no seu fuso horário. Altere aqui se necessário.',
    leaguesYouManage: 'Ligas que Você Gerencia',
    leaguesClickToView: 'Clique em uma liga para ver detalhes ou convidar amigos.',
    noLeaguesYet: 'Você ainda não criou nenhuma liga.',
    privateLabel: 'Privada',
    publicLabel: 'Pública',
    membersLabel: 'Membros',
    notificationsTitle: 'Notificações',
    noNotifications: 'Sem notificações',
    markAsRead: 'Marcar como lida',
    globalRankings: 'Ranking Global',
    upcomingRounds: 'Próximas Rodadas',
    activeRound: 'Rodada Ativa',
    pastRounds: 'Rodadas Anteriores',
    noActiveRound: 'Nenhuma rodada ativa — volte quando o próximo Grande Prêmio começar!',
    allEventsFinished: 'Todos os eventos encerrados',
    viewResults: 'Ver Resultados',
    live: 'AO VIVO',
    finished: 'ENCERRADO',
    betConfirmed: 'Aposta Confirmada!',
    yourSlipFor: 'Seu palpite para o',
    entryFeePaid: 'Taxa de Entrada Paga:',
    goodLuck: 'Boa Sorte!',
    sharePrediction: 'Compartilhar Previsão',
    sharing: 'Compartilhando...',
    shared: 'Compartilhado!',
    copiedToClipboard: 'Copiado!',
    downloadImage: 'Baixar Imagem',
    predictionsPlaced: 'previsão(ões)',
    share: 'Compartilhar',
    copied: 'Copiado',
    combo: 'Combo',
    p5Slip: 'P5 Slip',
    slotsUsed: 'Slots Usados',
    limitReachedMsg: 'Limite atingido para esta sessão! Tente outros eventos nesta Rodada.',
    betsRemainingMsg: 'Você ainda pode fazer mais apostas nesta sessão.',
    tapHint: 'Toque em um piloto ou equipe do grid e selecione um slot de previsão.',
    drivers: 'Pilotos',
    teams: 'Equipes',
    availableLabel: 'Disponível',
    predictionLabel: 'Previsão',
    constructorSlot: 'Slot de Construtor',
    awaiting: 'Aguardando...',
    selectP: 'Selecionar P',
    singleLabel: 'Simples',
    comboLabel: 'Combo',
    tryDifferentSession: 'Tente uma sessão diferente neste Grande Prêmio!',
    cancel: 'Cancelar',
    back: 'Voltar',
    chooseOtherEvent: 'Escolher Outro Evento',
    wait: 'Aguarde...',
    driversOnly: 'Só Pilotos',
    teamsOnly: 'Só Equipes',
    bothCombo: 'Ambos (Combo)',
    fillAllSlotsBoth: 'Preencha todos os 5 slots para Pilotos e Equipes.',
    fillAllSlots: 'Preencha todos os 5 slots de previsão.',
    betLimitReached: 'Você atingiu o limite de apostas para esta sessão.',
    diversifyRound: 'Diversificar Rodada',
    predict: 'Prever',
    mult: 'Mult',
    of: 'de',
    leagueNamePlaceholder: 'Nome da Liga',
    shortDescPlaceholder: 'Descrição Curta',
    enableChat: 'Ativar Chat',
    addPrize: 'Adicionar Prêmio',
    prizeTitlePlaceholder: 'Título do Prêmio (Máx 40 caracteres)',
    imageUrlPlaceholder: 'Enviar Imagem',
    uploadPrizeImage: 'Enviar Imagem do Prêmio',
    imageUploaded: 'Imagem Enviada ✓',
    prizeRulesPlaceholder: 'Regras e Descrição do Prêmio (Máx 500 caracteres)',
    remaining: 'restantes',
    createBtn: 'Criar',
    joined: 'Entrou',
    generalScoreboard: 'Classificação Geral',
    eventHistoryTab: 'Histórico de Eventos',
    paddockChat: 'Chat do Paddock',
    joining: 'Entrando...',
    joinGrid: 'Entrar no Grid',
    leaveLeague: 'Sair da Liga',
    copyInviteBtn: 'Copiar Convite',
    inviteMemberPlaceholder: 'Convidar membro por usuário...',
    sendInvite: 'Enviar Convite',
    seasonPts: 'PTS Temporada',
    unsuspend: 'Reativar',
    suspend: 'Suspender',
    banUser: 'Banir Usuário',
    pastSessions: 'Resultados de Sessões Anteriores',
    leagueEntries: 'Entradas da Liga',
    viewScoreboardLink: 'Ver Classificação',
    noEventsYet: 'Nenhum evento concluído nesta temporada ainda.',
    leagueCommandCentre: 'Centro de Comando da Liga',
    enableTelemetry: 'Ativar Telemetria de Membros (Chat)',
    customSeasonalPrize: 'Prêmio Personalizado da Temporada',
    prizeDesignation: 'Designação do Prêmio',
    prizeDesignationPlaceholder: 'ex: Capacete de Ouro Lendário',
    visualEvidence: 'Evidência Visual (Enviar Imagem)',
    sportingRegulations: 'Regulamento Esportivo (Regras)',
    describePrize: 'Descreva como os membros ganham este prêmio...',
    finalizeChanges: 'Finalizar Alterações Esportivas',
    seasonPrizeLabel: 'Prêmio da Temporada:',
    enterInviteCode: 'Digite o Código de Convite:',
    leaveConfirm: 'Tem certeza que deseja sair desta liga?',
    inviteLinkCopied: 'Link de convite copiado!',
    invitationSent: 'Convite enviado para',
    leagueSettingsUpdated: 'Configurações da liga atualizadas!',
    confirmAction: 'Confirmar ação:',
    round: 'Rodada',
    resultsLabel: 'Resultados:',
    officialClassification: 'Classificação Oficial',
    podiumPayouts: 'Pódio e Pagamentos',
    fullScoreboard: 'Classificação Completa',
    officialTop5: 'Top 5 Oficial',
    prizeDistribution: 'Distribuição de Prêmios',
    totalPurse: 'Prêmio Total',
    winnersLabel: 'Vencedores',
    participantLabel: 'Participante',
    pointsLabel: 'Pontos',
    prizeLabel: 'Prêmio',
    viewAllEntries: 'Ver todas as entradas na Classificação',
    noParticipantsEarned: 'Nenhum participante ganhou pontos nesta sessão.',
    eventScoreboard: 'Classificação do Evento',
    searchUser: 'Buscar usuário...',
    rankLabel: 'Posição',
    userLabel: 'Usuário',
    p15Prediction: 'Previsão P1-P5',
    noEntriesFound: 'Nenhuma entrada encontrada para sua busca.',
    noPrediction: 'Sem previsão',
    bannedFromLeague: 'Você foi banido desta liga.',
    leagueChatTitle: 'Chat da Liga',
    messagesRemovedNote: 'Mensagens são removidas após 10 dias.',
    suspendedFromChat: 'Você está suspenso do chat',
    typeMessage: 'Digite uma mensagem...',
    getCoins: 'Obter Fun Coins',
    freeRewards: 'Recompensas Grátis',
    watchEarn: 'Assistir e Ganhar',
    watchAdDesc: 'Assista a um breve clipe de patrocínio dos nossos parceiros para ganhar moedas grátis para sua próxima previsão.',
    adPlaying: 'Anúncio Reproduzindo...',
    watchAd: 'Assistir Anúncio',
    adRewardsDisabled: 'Recompensas de anúncios desativadas no momento.',
    coinsAdded: 'Moedas Adicionadas!',
    passwordsDontMatch: 'As senhas não coincidem',
    minAge18: 'Idade mínima é 18 anos',
    pleaseAcceptTerms: 'Por favor, aceite os termos e condições',
    selectCountry: 'Selecionar...',
    locationNotice: 'Sua localização será detectada automaticamente para definir seu país.',
    leaveSiteTitle: 'Sair do F1™ Poolers?',
    leaveSiteMessage: 'Tem certeza que deseja sair do site?',
    leaveSiteStay: 'Não, ficar no F1™ Poolers',
    leaveSiteLeave: 'Sim, sair do site'
  },
  es: {
    welcome: 'Bienvenido al Paddock',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    howToPlay: 'Cómo Jugar y Puntuación',
    username: 'Usuario',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    age: 'Edad',
    country: 'País',
    terms: 'Acepto los Términos y Condiciones',
    raceNow: '¡A Correr!',
    dashboard: 'Tablero',
    adminPanel: 'Panel Admin',
    rankings: 'Clasificación Global',
    leagues: 'Ligas',
    placeBet: 'Hacer Predicción',
    bettingClosed: 'Apuestas Cerradas',
    entryFee: 'Costo de Entrada',
    prizePool: 'Pozo de Premios',
    multiplier: 'Multiplicador',
    confirmBet: 'Confirmar Apuesta',
    pointsBreakdown: 'Desglose de Puntos',
    exactMatch: 'Coincidencia Exacta',
    partialMatch: 'Coincidencia Parcial',
    howToBet: 'Cómo Apostar',
    detailedScoring: 'Puntuación Detallada',
    socialLeagues: 'Social y Ligas',
    welcomeTab: 'Bienvenida',
    acceptTerms: '¡Aceptar y Correr!',
    manualTitle: 'F1™ Poolers: Reglamento Deportivo',
    welcomeTitle: 'Bienvenido a F1™ Poolers',
    welcomeSubtitle: 'El juego definitivo de predicción de F1. Supera a tus rivales, escala en la clasificación y demuestra que conoces la Fórmula 1 mejor que nadie.',
    howItWorksTitle: 'Cómo Funciona',
    howItWorksStep1Title: 'Elige una Sesión',
    howItWorksStep1Desc: 'Cada fin de semana de Gran Premio tiene varias sesiones: Clasificación, Sprint y Carrera. Elige cuál quieres predecir.',
    howItWorksStep2Title: 'Predice el Top 5',
    howItWorksStep2Desc: 'Selecciona 5 pilotos (o equipos) y colócalos en orden de P1 a P5. Esa es tu papeleta de predicción.',
    howItWorksStep3Title: 'Gana Puntos y Monedas',
    howItWorksStep3Desc: 'Después de la sesión, tus predicciones se puntúan. Las coincidencias exactas de posición otorgan muchos puntos; tener el piloto correcto en el top 5 pero en la posición incorrecta aún otorga un bono parcial.',
    whatAreFunCoinsTitle: '¿Qué son las Fun-Coins?',
    whatAreFunCoinsDesc: 'Las Fun-Coins son la moneda del juego que usas para hacer predicciones. NO son dinero real — este es un juego de estrategia gratuito. Recibes 50 Fun-Coins gratis cada vez que se abre un nuevo fin de semana de carreras, así que siempre puedes jugar.',
    whatAreFunCoinsExtra: 'Cuantas más Fun-Coins tengas, más predicciones podrás hacer en diferentes sesiones — ¡dándote más oportunidades de sumar puntos y escalar en la clasificación!',
    whatArePointsTitle: '¿Qué son los Puntos?',
    whatArePointsDesc: 'Los puntos son tu puntuación. Determinan tu posición en la Clasificación Global y dentro de tus Ligas. Cuanto más precisas sean tus predicciones, más puntos ganas. Los puntos se acumulan a lo largo de toda la temporada.',
    bettingStrategyTitle: 'Consejos de Estrategia',
    strategyTip1Title: 'Apuesta Temprano',
    strategyTip1Desc: 'Las predicciones hechas días antes de la sesión bloquean un multiplicador más alto (hasta 5×), aumentando enormemente tus puntos.',
    strategyTip2Title: 'Pilotos vs Equipos',
    strategyTip2Desc: 'Las apuestas por pilotos pagan más puntos pero son más difíciles de acertar. Las apuestas por equipos dan el doble de cobertura (dos autos) al 50% de puntos — genial para sesiones impredecibles.',
    strategyTip3Title: 'Apuestas Combo',
    strategyTip3Desc: 'Envía una predicción de Piloto Y una de Equipo en la misma sesión para una apuesta Combo. Cuesta más Fun-Coins, pero ganas puntos de ambas papeletas.',
    strategyTip4Title: 'Busca el Jackpot',
    strategyTip4Desc: '¡Si predices los pilotos exactos de P1-P5 en el orden correcto, activas el Protocolo Jackpot y ganas una parte de todo el pozo de premios acumulado! Si nadie lo logra, el pozo se acumula para el mismo evento en la siguiente ronda — ¡haciendo el jackpot aún más grande!',
    readyToRace: 'Listo para correr? Explora las otras pestañas para tablas de puntuación detalladas, mecánica de multiplicadores y funcionalidades de liga.',
    langSelect: 'Seleccionar Idioma',
    multiplierTiers: 'Sistema de Multiplicadores',
    article1: 'Artículo 1.0: Asignación de Puntos',
    article1_1: 'Artículo 1.1: Estrategia de Constructores',
    article1_2: 'Artículo 1.2: El Gran Jackpot',
    article2: 'Artículo 2.0: Multiplicadores de Tiempo',
    economyTitle: 'Economía y Ganancias de Fun-Coins',
    roundBonus: 'Bono de Ronda',
    adRewards: 'Premios por Anuncios',
    storeBundles: 'Paquetes de Tienda',
    jackpotShares: 'Cuotas del Jackpot',
    chooseStrategy: 'Elegir Estrategia',
    theGrid: 'La Parrilla',
    finalize: 'Finalizar',
    platinum: 'Platino',
    gold: 'Oro',
    silver: 'Plata',
    standard: 'Estándar',
    economyDesc: 'Cada vez que se agrega un nuevo fin de semana de carreras al calendario, cada jugador activo recibe 50 Fun-Coins automáticamente para asegurar que la parrilla se mantenga llena.',
    adRewardsDesc: 'Tener más Fun-Coins significa que puedes hacer más predicciones en diferentes sesiones y tipos de eventos, maximizando tus oportunidades de ganar puntos y triunfar.',
    storeBundlesDesc: 'Para los grandes apostadores que buscan unirse a múltiples ligas o eventos de alta entrada, los "Cofres de Campeonato" y "Paquetes de Piloto" están disponibles en la tienda.',
    betStep1: 'Elige entre Pilotos Individuales o Constructores.',
    betStep2: 'Toca un piloto/equipo de la parrilla y selecciona un espacio de predicción (P1-P5).',
    betStep3: 'Pulsa Confirmar Predicción para bloquear tu posición y el multiplicador actual.',
    multiplierIntro: 'El sistema de multiplicadores premia el análisis temprano. Cuanto antes bloquees tu predicción antes del inicio de la sesión, mayor será tu puntuación final.',
    multiplierLock: 'El multiplicador se bloquea permanentemente en el momento en que haces clic en "Confirmar Predicción". Cambiar tu predicción después de la confirmación resultará en la aplicación del multiplicador actual del momento de la nueva confirmación.',
    constructorStrategyDesc: 'Las apuestas por equipo funcionan como una cobertura. Ganas el 50% de los puntos de Piloto si cualquier piloto de ese equipo termina en el lugar previsto.',
    jackpotProtocolDesc: 'Una "Predicción Perfecta" (acertar los pilotos exactos de P1-P5 en orden) activa el Protocolo del Jackpot. El pozo total acumulado se divide equitativamente entre todos los jugadores que logren el resultado perfecto. Si nadie logra una Predicción Perfecta, todo el pozo se acumula para el mismo tipo de evento en la siguiente ronda, ¡aumentando el jackpot hasta que alguien lo reclame!',
    leagueIntro: 'Competir globalmente es el estándar; competir en tu propia Liga es donde se forjan las leyendas. Las ligas son comunidades privadas o públicas donde compites contra tu círculo íntimo.',
    privacyProtocol: 'Protocolo de Privacidad: Los administradores pueden cerrar las ligas con códigos de invitación únicos. Solo los miembros verificados pueden entrar en la simulación.',
    customTrophies: 'Trofeos Personalizados: Los administradores de la liga pueden establecer premios "Físicos" o "Digitales" específicos (por ejemplo, merchandising personalizado o títulos) para los ganadores de la temporada.',
    fullModeration: 'Moderación Total: Los administradores tienen el poder de suspender o expulsar a los miembros que violen el código de conducta deportiva.',
    paddockChatIntro: 'El Chat del Paddock: Telemetría y discusión en tiempo real.',
    globalRankHighlight: 'Resaltado de Rango Global: Los jugadores con mejor rango global se resaltan automáticamente en los chats de la liga con insignias de "Apostador VIP".',
    realTimeTelemetry: 'Telemetría en Tiempo Real: Chatea sobre los resultados de las carreras al instante con comunicación cifrada de la liga.',
    reactionsDesc: 'Reacciones: Da me gusta o no me gusta a las predicciones compartidas en el chat para mostrar tu apoyo o rivalidad.',
    driverPredictionsDesc: 'Predice el orden exacto de llegada de los 5 primeros pilotos. Las coincidencias exactas otorgan puntos máximos. Las coincidencias parciales (piloto en el top 5 pero posición incorrecta) otorgan un bono de seguridad fijo.',
    teamPredictionsDesc: 'Los equipos otorgan el 50% del total de puntos de Piloto para esa posición. Si cualquier auto de tu equipo elegido termina en la posición prevista, ganas los puntos. Esta es una estrategia de menor riesgo ideal para sesiones caóticas.',
    teamMainRacePoints: 'Puntos de Carrera Principal por Equipo:',
    teamStrategyAdvantages: 'Ventajas de Estrategia por Equipo:',
    doubleCarCoverage: 'Cobertura de Dos Autos',
    safetyPartialPoints: 'Puntos Parciales de Seguridad',
    jackpotEligibility: 'Elegibilidad para Jackpot',
    jackpotTrigger: 'Solo las predicciones exactas de Pilotos P1-P5 activan este protocolo. ¡Los jackpots no reclamados se acumulan para la siguiente ronda!',
    leagueTelemetry: 'TELEMETRÍA DE LA LIGA',
    createYourPaddock: 'Crea Tu Paddock',
    createPaddockDesc: 'Inicia ligas privadas para tus compañeros de trabajo, familia o fanáticos de carreras globales. Personaliza el nombre, descripción y accesibilidad de tu sala de simulación.',
    customTrophiesRewards: 'Trofeos y Recompensas Personalizadas',
    customTrophiesDesc: 'Los administradores pueden definir premios de temporada, incluidos artículos físicos o títulos digitales. Crea apuestas que importen a tu grupo y rastrea quién domina el podio.',
    socialCommunication: 'Comunicación Social',
    chatExample1: '¡Max definitivamente tomará P1 este fin de semana!',
    chatExample2: '¡De ninguna manera, viste el ritmo de Ferrari en los EL2?',
    realTimeChat: 'Chat en Tiempo Real:',
    realTimeChatDesc: 'Telemetría instantánea del paddock y charlas entre sesiones.',
    reactions: 'Reacciones:',
    reactionsFeatureDesc: 'Dale me gusta o no me gusta a las predicciones para avivar el fuego competitivo.',
    highRollerBadges: 'Insignias Apostador VIP:',
    highRollerBadgesDesc: 'Los mejores jugadores globales se identifican automáticamente en los chats de la liga.',
    moderation: 'Moderación:',
    moderationDesc: 'Los administradores pueden suspender o expulsar a los usuarios para mantener el ambiente deportivo.',
    messageClearNote: 'Nota: Los mensajes se eliminan automáticamente después de 10 días para mantener el paddock fresco.',
    multiplierMechanics: 'Mecánica de Multiplicadores',
    driverPredictions: 'Predicciones de Pilotos',
    teamPredictions: 'Predicciones de Equipos',
    perfectScore: 'Puntuación Perfecta',
    mainRace: 'Carrera Principal',
    qualifying: 'Clasificación',
    sprintRace: 'Carrera Sprint',
    pos: 'Pos',
    exact: 'Exacto',
    anyT5: 'Cualquier T5',
    tapGrid: 'Toca la Parrilla',
    selectSlot: 'Selecciona Espacio',
    tapAnyDriver: 'Toca cualquier piloto de la parrilla y selecciona tu posición deseada P1-P5.',
    termsAgree: 'Acepto los',
    termsAndConditions: 'Términos y Condiciones',
    close: 'Cerrar',
    biometricLogin: 'Iniciar con Biometría',
    passwordMustBe5Digits: 'La contraseña debe tener exactamente 5 números',
    passwordHint: 'Solo 5 dígitos (ej: 12345)',
    statistics: 'Estadísticas de Temporada',
    statsNoData: 'Sin Estadísticas Disponibles',
    statsNoDataDesc: 'Los resultados aparecerán aquí cuando se completen los eventos.',
    statsEventsRecorded: 'Eventos Registrados',
    statDrivers: 'Pilotos',
    statTeams: 'Equipos',
    statDriver: 'Piloto',
    statTeam: 'Equipo',
    statPts: 'PTS',
    statWins: 'Victorias',
    statPodiums: 'Podios',
    statTop5: 'Top 5',
    statEntries: 'Entradas',
    statAvgPos: 'Pos Prom',
    statBestPos: 'Mejor',
    statEventBreakdown: 'Desglose por Evento',
    statFilter_all: 'Todos',
    statFilter_race: 'Carrera',
    statFilter_qualifying: 'Clasificación',
    statFilter_sprint: 'Sprint',
    usernameHint: 'Máx 8 caracteres, sin espacios',
    usernameInvalid: 'El usuario debe tener máximo 8 caracteres sin espacios',
    recoveryTitle: 'Agregar Contacto de Recuperación',
    recoveryMessage: 'Te recomendamos agregar un email o teléfono a tu perfil. Esta es la única forma de recuperar tus credenciales si las olvidas o pierdes. F1 Poolers nunca enviará mensajes a tu información de contacto — se usa únicamente para recuperar tu cuenta.',
    recoveryGoToProfile: 'Ir al Perfil',
    recoveryDismissBtn: 'Ahora no, arriesgaré perder mis puntos',
    inviteFriends: 'Invita a tus amigos a competir contigo',
    inviteShareVia: 'Compartir vía',
    inviteCopied: '¡Copiado!',
    inviteCopyUrl: 'Copiar URL',
    inviteMessage: '¿Crees que puedes superarme en predicciones de F1? \u{1F3CE}\u{FE0F} Únete a mí en F1 Poolers \u2014 elige tus Top 5 pilotos y equipos, sube en el ranking y demuestra quién es el verdadero campeón del paddock. ¡Gratis, pura diversión! ¡Vamos a correr! \u{1F3C1}',
    inviteMessageShort: '¿Crees que puedes superar mis predicciones de F1? \u{1F3CE}\u{FE0F} ¡Únete a mí en F1 Poolers! Gratis, divertido y competitivo.',
    inviteEmailSubject: '¡Únete a mí en F1 Poolers! \u{1F3CE}\u{FE0F}',
    inviteInstagramHint: '¡Mensaje copiado! Pégalo en Instagram.',
    userSettings: 'Configuración',
    profile: 'Perfil',
    myLeagues: 'Mis Ligas',
    memberSince: 'Miembro desde',
    avatarHint: 'Toca el ícono de la cámara para subir un nuevo avatar (máx 2MB)',
    recoveryContactLabel: 'Contacto de Recuperación',
    recoveryContactHint: 'Agrega un email o teléfono para recuperar tu cuenta si olvidas tus credenciales. Nunca enviaremos mensajes a estos contactos.',
    email: 'Email',
    phone: 'Teléfono',
    saving: 'Guardando...',
    saveChanges: 'Guardar Cambios',
    profileUpdated: '¡Perfil actualizado!',
    profileUpdateFailed: 'Error al actualizar perfil.',
    imageTooLarge: 'La imagen debe ser menor de 2MB',
    timezone: 'Zona Horaria',
    timezoneHint: 'Todos los horarios de eventos se muestran en tu zona horaria. Cámbiala aquí si es necesario.',
    leaguesYouManage: 'Ligas que Administras',
    leaguesClickToView: 'Toca una liga para ver detalles o invitar amigos.',
    noLeaguesYet: 'Aún no has creado ninguna liga.',
    privateLabel: 'Privada',
    publicLabel: 'Pública',
    membersLabel: 'Miembros',
    notificationsTitle: 'Notificaciones',
    noNotifications: 'Sin notificaciones',
    markAsRead: 'Marcar como leída',
    globalRankings: 'Clasificación Global',
    upcomingRounds: 'Próximas Rondas',
    activeRound: 'Ronda Activa',
    pastRounds: 'Rondas Anteriores',
    noActiveRound: '¡Sin ronda activa — vuelve cuando comience el próximo Gran Premio!',
    allEventsFinished: 'Todos los eventos finalizados',
    viewResults: 'Ver Resultados',
    live: 'EN VIVO',
    finished: 'FINALIZADO',
    betConfirmed: '¡Apuesta Confirmada!',
    yourSlipFor: 'Tu predicción para',
    entryFeePaid: 'Costo de Entrada Pagado:',
    goodLuck: '¡Buena Suerte!',
    sharePrediction: 'Compartir Predicción',
    sharing: 'Compartiendo...',
    shared: '¡Compartido!',
    copiedToClipboard: '¡Copiado!',
    downloadImage: 'Descargar Imagen',
    predictionsPlaced: 'predicción(es)',
    share: 'Compartir',
    copied: 'Copiado',
    combo: 'Combo',
    p5Slip: 'P5 Slip',
    slotsUsed: 'Slots Usados',
    limitReachedMsg: '¡Límite alcanzado para esta sesión! Prueba otros eventos en esta Ronda.',
    betsRemainingMsg: 'Aún puedes hacer más apuestas para esta sesión.',
    tapHint: 'Toca un piloto o equipo de la parrilla y selecciona una posición de predicción.',
    drivers: 'Pilotos',
    teams: 'Equipos',
    availableLabel: 'Disponible',
    predictionLabel: 'Predicción',
    constructorSlot: 'Slot de Constructor',
    awaiting: 'Esperando...',
    selectP: 'Seleccionar P',
    singleLabel: 'Simple',
    comboLabel: 'Combo',
    tryDifferentSession: '¡Prueba una sesión diferente en este Gran Premio!',
    cancel: 'Cancelar',
    back: 'Volver',
    chooseOtherEvent: 'Elegir Otro Evento',
    wait: 'Espera...',
    driversOnly: 'Solo Pilotos',
    teamsOnly: 'Solo Equipos',
    bothCombo: 'Ambos (Combo)',
    fillAllSlotsBoth: 'Completa los 5 slots para Pilotos y Equipos.',
    fillAllSlots: 'Completa los 5 slots de predicción.',
    betLimitReached: 'Has alcanzado el límite de apuestas para esta sesión.',
    diversifyRound: 'Diversificar Ronda',
    predict: 'Predecir',
    mult: 'Mult',
    of: 'de',
    leagueNamePlaceholder: 'Nombre de la Liga',
    shortDescPlaceholder: 'Descripción Corta',
    enableChat: 'Activar Chat',
    addPrize: 'Agregar Premio',
    prizeTitlePlaceholder: 'Título del Premio (Máx 40 caracteres)',
    imageUrlPlaceholder: 'Subir Imagen',
    uploadPrizeImage: 'Subir Imagen del Premio',
    imageUploaded: 'Imagen Subida ✓',
    prizeRulesPlaceholder: 'Reglas y Descripción del Premio (Máx 500 caracteres)',
    remaining: 'restantes',
    createBtn: 'Crear',
    joined: 'Unido',
    generalScoreboard: 'Clasificación General',
    eventHistoryTab: 'Historial de Eventos',
    paddockChat: 'Chat del Paddock',
    joining: 'Uniéndose...',
    joinGrid: 'Unirse al Grid',
    leaveLeague: 'Salir de la Liga',
    copyInviteBtn: 'Copiar Invitación',
    inviteMemberPlaceholder: 'Invitar miembro por usuario...',
    sendInvite: 'Enviar Invitación',
    seasonPts: 'PTS Temporada',
    unsuspend: 'Reactivar',
    suspend: 'Suspender',
    banUser: 'Banear Usuario',
    pastSessions: 'Resultados de Sesiones Anteriores',
    leagueEntries: 'Entradas de la Liga',
    viewScoreboardLink: 'Ver Clasificación',
    noEventsYet: 'Ningún evento completado en esta temporada aún.',
    leagueCommandCentre: 'Centro de Comando de la Liga',
    enableTelemetry: 'Activar Telemetría de Miembros (Chat)',
    customSeasonalPrize: 'Premio Personalizado de Temporada',
    prizeDesignation: 'Designación del Premio',
    prizeDesignationPlaceholder: 'ej: Casco de Oro Legendario',
    visualEvidence: 'Evidencia Visual (Subir Imagen)',
    sportingRegulations: 'Reglamento Deportivo (Reglas)',
    describePrize: 'Describe cómo los miembros ganan este premio...',
    finalizeChanges: 'Finalizar Cambios Deportivos',
    seasonPrizeLabel: 'Premio de Temporada:',
    enterInviteCode: 'Ingresa el Código de Invitación:',
    leaveConfirm: '¿Estás seguro de que quieres salir de esta liga?',
    inviteLinkCopied: '¡Enlace de invitación copiado!',
    invitationSent: 'Invitación enviada a',
    leagueSettingsUpdated: '¡Configuración de la liga actualizada!',
    confirmAction: 'Confirmar acción:',
    round: 'Ronda',
    resultsLabel: 'Resultados:',
    officialClassification: 'Clasificación Oficial',
    podiumPayouts: 'Podio y Pagos',
    fullScoreboard: 'Clasificación Completa',
    officialTop5: 'Top 5 Oficial',
    prizeDistribution: 'Distribución de Premios',
    totalPurse: 'Premio Total',
    winnersLabel: 'Ganadores',
    participantLabel: 'Participante',
    pointsLabel: 'Puntos',
    prizeLabel: 'Premio',
    viewAllEntries: 'Ver todas las entradas en la Clasificación',
    noParticipantsEarned: 'Ningún participante ganó puntos en esta sesión.',
    eventScoreboard: 'Clasificación del Evento',
    searchUser: 'Buscar usuario...',
    rankLabel: 'Posición',
    userLabel: 'Usuario',
    p15Prediction: 'Predicción P1-P5',
    noEntriesFound: 'No se encontraron entradas para tu búsqueda.',
    noPrediction: 'Sin predicción',
    bannedFromLeague: 'Has sido baneado de esta liga.',
    leagueChatTitle: 'Chat de la Liga',
    messagesRemovedNote: 'Los mensajes se eliminan después de 10 días.',
    suspendedFromChat: 'Estás suspendido del chat',
    typeMessage: 'Escribe un mensaje...',
    getCoins: 'Obtener Fun Coins',
    freeRewards: 'Recompensas Gratis',
    watchEarn: 'Ver y Ganar',
    watchAdDesc: 'Mira un breve clip de patrocinio de nuestros socios para ganar monedas gratis para tu próxima predicción.',
    adPlaying: 'Anuncio Reproduciéndose...',
    watchAd: 'Ver Anuncio',
    adRewardsDisabled: 'Recompensas de anuncios desactivadas actualmente.',
    coinsAdded: '¡Monedas Agregadas!',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    minAge18: 'La edad mínima es 18 años',
    pleaseAcceptTerms: 'Por favor, acepta los términos y condiciones',
    selectCountry: 'Seleccionar...',
    locationNotice: 'Tu ubicación será detectada automáticamente para establecer tu país.',
    leaveSiteTitle: '¿Salir de F1™ Poolers?',
    leaveSiteMessage: '¿Estás seguro de que quieres salir del sitio?',
    leaveSiteStay: 'No, quedarme en F1™ Poolers',
    leaveSiteLeave: 'Sí, salir del sitio'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};